naxx: refine some timers from logs
DeadlyBossMods/DBM-Classic pull request #612
Opened 2020-10-24 09:08 UTC by venuatu

from aggregating ptr logs, you could see the timer stats in the below if you want to do this differently
https://gist.github.com/venuatu/a9f2b4310d86bbb1f07534555271c2f6

2020-10-24 13:37 UTC, MysticalOS requested changes
Several of these timers were not adjusted even though you added comments?

On noth, the adds timers are hard coded so changing timer in object literally does nothing. It doesn't matter if that says 0 or math.huge . EACh set of adds has it's own timer and if they aren't correct EACH set of adds needs updated timer, not the object.

Timers like decimate having that huge of a variation need further review. if timer is 120-182 I'll likely remove the timer than put that kind of variation in. I'd check if that timer is perhaps health based and not time based at all. Check boss health at time of each cast in multiple logs. It could also be dual condition, min time + health threshold. when it comes off CD it'll activate immediately but only if boss is below certain health threshold else it won't activate UNTIL boss is below that health.

Timers are always rounded down to 10th decimal. if a timer is 40.43 just put 40.4 for timer. don't leave it at 40.5 if that's what's set because then the debug will be triggered.

Is injection debuff really variable? or did you mistake that for CD timer? that's debuff duration timer in DBM, the debuff going out was always too variable to have a CD timer that's why there isn't one and only timer DBM showed was Debuff expiring off players. I can't imagine the debuff being 6-17 seconds.

2020-10-24 16:55 UTC, venuatu commented
noth: that 34 second is for the minimum blink away cd time, maybe that should be a new timer

gluth decimate: need to check that in logs, one of them had two decimates, which would be interesting to look into

grobbulus injection: yep you got that right, will drop the comment

2020-10-25 07:01 UTC, venuatu commented
I dropped the buff active timers, updated some times and fixed up the merge, the times should be good to go

2020-10-25 15:01 UTC, MysticalOS approved these changes

2020-10-25 15:02 UTC, merged