naxx/kt: Add fissure yell and include target
DeadlyBossMods/DBM-Classic pull request #687
Opened 2021-02-15 08:43 UTC by venuatu

I saw that a weakaura was giving out personal warnings for this and what do you know, this actually targets someone

2021-02-15 08:49 UTC, MysticalOS commented
I'll double check to mae sure success event actually has target info in it.. if it does some tweaaks should be made such as a nearby speciall warning if person it's on is within 6 yards for example.

that basically goese if on you warn you, elseif checknearby 6 then warn it's near you on targetname else generic target warning. Probably a template/example of it somewhere. Search for a mod using self:Checknearby()

2021-02-15 17:54 UTC, MysticalOS requested changes
use mod:NewSpecialWarningClose instead of mod:NewSpecialWarningTarget for the near warning

2021-02-16 21:23 UTC, wallrik commented
I guess you confirmed the event already @venuatu, but just wanted to say I also confirmed it. It does have a target on `SPELL_CAST_SUCCESS`.
```
<30.01 21:20:12> [DBM_Announce] Shadow Fissure#136134#spell#27810#Kel'Thuzad
<30.01 21:20:12> [CLEU] SPELL_CAST_SUCCESS#Creature-0-4458-533-8625-15990-00002C11CC#Kel'Thuzad#Player-4456-02394500#Eldarathi#Shadow Fissure#nil#nil
<30.02 21:20:12> [CLEU] SPELL_SUMMON#Creature-0-4458-533-8625-15990-00002C11CC#Kel'Thuzad#Creature-0-4458-533-8625-16129-00002C28FC#Shadow Fissure#Shadow Fissure#nil#nil

<33.64 21:20:16> [CLEU] SPELL_CAST_SUCCESS#Creature-0-4458-533-8625-16129-00002C28FC#Shadow Fissure##nil#Void Blast#nil#nil
<33.67 21:20:16> [CLEU] SPELL_DAMAGE#Creature-0-4458-533-8625-16129-00002C28FC#Shadow Fissure#Player-4456-021C407D#Rhaatid#Void Blast
```

2021-02-16 21:23 UTC, QartemisT approved these changes

2021-02-16 21:55 UTC, MysticalOS approved these changes

2021-02-16 21:55 UTC, merged